-- Auto-generated by migrate/gen_supabase_schema.py — do not edit by hand.
-- Postgres/Supabase schema mirroring fifa_2026.db. Safe to re-run.
create schema if not exists public;

create table if not exists public."bet_legs" (
  "leg_id" bigint,
  "bet_id" bigint not null,
  "match_num" bigint not null,
  "pick_side" text not null,
  "pick_team" text not null,
  "odds" double precision,
  "model_prob" double precision,
  "result" text not null,
  primary key ("leg_id")
);
alter table public."bet_legs" enable row level security;
drop policy if exists "bet_legs_public_read" on public."bet_legs";

create table if not exists public."bets" (
  "bet_id" bigint,
  "name" text not null,
  "bet_type" text not null,
  "stake" double precision not null,
  "currency" text not null,
  "placed_date" text not null,
  "total_odds" double precision,
  "status" text not null,
  "payout" double precision,
  "profit" double precision,
  "settled_at" text,
  primary key ("bet_id")
);
alter table public."bets" enable row level security;
drop policy if exists "bets_public_read" on public."bets";

create table if not exists public."champion_predictions" (
  "id" bigint,
  "snapshot_date" text not null,
  "team" text not null,
  "market_prob" double precision,
  "opta_prob" double precision,
  "model_prob" double precision,
  "blended_raw" double precision,
  "blended_ewma" double precision,
  "rank" bigint,
  "delta" double precision,
  primary key ("id")
);
alter table public."champion_predictions" enable row level security;
drop policy if exists "champion_predictions_public_read" on public."champion_predictions";
create policy "champion_predictions_public_read" on public."champion_predictions" for select using (true);

create table if not exists public."external_champion_predictions" (
  "source_key" text not null,
  "snapshot_date" text not null,
  "team" text not null,
  "champion_prob" double precision not null,
  "source_url" text not null,
  "data_quality" text not null,
  "ingested_at" text not null,
  primary key ("source_key", "snapshot_date", "team")
);
alter table public."external_champion_predictions" enable row level security;
drop policy if exists "external_champion_predictions_public_read" on public."external_champion_predictions";
create policy "external_champion_predictions_public_read" on public."external_champion_predictions" for select using (true);

create table if not exists public."external_match_predictions" (
  "source_key" text not null,
  "snapshot_date" text not null,
  "match_num" bigint,
  "home_team" text,
  "away_team" text,
  "home_prob" double precision,
  "draw_prob" double precision,
  "away_prob" double precision,
  "pred_score" text,
  "source_url" text not null,
  "data_quality" text not null,
  "ingested_at" text not null,
  primary key ("source_key", "snapshot_date", "match_num")
);
alter table public."external_match_predictions" enable row level security;
drop policy if exists "external_match_predictions_public_read" on public."external_match_predictions";
create policy "external_match_predictions_public_read" on public."external_match_predictions" for select using (true);

create table if not exists public."groups" (
  "id" bigint,
  "group_letter" text not null,
  "team_name" text not null,
  primary key ("id")
);
alter table public."groups" enable row level security;
drop policy if exists "groups_public_read" on public."groups";
create policy "groups_public_read" on public."groups" for select using (true);

create table if not exists public."matches" (
  "match_num" bigint,
  "group_or_stage" text not null,
  "date" text,
  "time" text,
  "home_team" text,
  "away_team" text,
  "stadium" text,
  "city" text,
  "score" text,
  "home_goals" bigint,
  "away_goals" bigint,
  "status" text not null,
  "home_pre_match_elo" double precision,
  "away_pre_match_elo" double precision,
  "pred_home_win_prob" double precision,
  "pred_draw_prob" double precision,
  "pred_away_win_prob" double precision,
  "pred_home_expected_goals" double precision,
  "pred_away_expected_goals" double precision,
  "pred_score" text,
  "odds_home" double precision,
  "odds_draw" double precision,
  "odds_away" double precision,
  "ev_home" double precision,
  "ev_draw" double precision,
  "ev_away" double precision,
  "kelly_home" double precision,
  "kelly_draw" double precision,
  "kelly_away" double precision,
  "odds_source" text,
  "odds_last_update" text,
  "odds_bookmaker_keys" text,
  "last_updated" text,
  "odds_home_pinnacle" double precision,
  "odds_draw_pinnacle" double precision,
  "odds_away_pinnacle" double precision,
  "ev_home_pinnacle" double precision,
  "ev_draw_pinnacle" double precision,
  "ev_away_pinnacle" double precision,
  "kelly_home_pinnacle" double precision,
  "kelly_draw_pinnacle" double precision,
  "kelly_away_pinnacle" double precision,
  "odds_home_williamhill" double precision,
  "odds_draw_williamhill" double precision,
  "odds_away_williamhill" double precision,
  "ev_home_williamhill" double precision,
  "ev_draw_williamhill" double precision,
  "ev_away_williamhill" double precision,
  "kelly_home_williamhill" double precision,
  "kelly_draw_williamhill" double precision,
  "kelly_away_williamhill" double precision,
  "odds_home_draftkings" double precision,
  "odds_draw_draftkings" double precision,
  "odds_away_draftkings" double precision,
  "ev_home_draftkings" double precision,
  "ev_draw_draftkings" double precision,
  "ev_away_draftkings" double precision,
  "kelly_home_draftkings" double precision,
  "kelly_draw_draftkings" double precision,
  "kelly_away_draftkings" double precision,
  "home_xg" double precision,
  "away_xg" double precision,
  "home_possession" double precision,
  "away_possession" double precision,
  "home_shots" double precision,
  "away_shots" double precision,
  primary key ("match_num")
);
alter table public."matches" enable row level security;
drop policy if exists "matches_public_read" on public."matches";
create policy "matches_public_read" on public."matches" for select using (true);

create table if not exists public."prediction_sources" (
  "source_key" text,
  "source_name" text not null,
  "source_url" text not null,
  "source_type" text not null,
  "access_tier" text not null,
  "sync_mode" text not null,
  "free_direct" bigint not null,
  "coverage" text not null,
  "trust_tier" text not null,
  "snapshot_date" text,
  "last_sync_at" text,
  "last_sync_status" text,
  "notes" text,
  primary key ("source_key")
);
alter table public."prediction_sources" enable row level security;
drop policy if exists "prediction_sources_public_read" on public."prediction_sources";
create policy "prediction_sources_public_read" on public."prediction_sources" for select using (true);

create table if not exists public."teams" (
  "id" bigint,
  "name" text not null,
  "confederation" text,
  "elo_rating" double precision not null,
  "fifa_rank" bigint not null,
  "pi_rating_home" double precision not null,
  "pi_rating_away" double precision not null,
  "berrar_att" double precision not null,
  "berrar_def" double precision not null,
  "fbref_xg_diff" double precision not null,
  "injury_count" bigint not null,
  "sentiment_score" double precision not null,
  "opta_win_prob" double precision not null,
  primary key ("id")
);
alter table public."teams" enable row level security;
drop policy if exists "teams_public_read" on public."teams";
create policy "teams_public_read" on public."teams" for select using (true);
