#!/usr/bin/env python3
"""Generate Postgres (Supabase) DDL from the live SQLite schema.

Keeps supabase/schema.sql in lock-step with fifa_2026.db so the Supabase backend
mirrors exactly what the daily pipeline produces. Run after any schema change:

    python migrate/gen_supabase_schema.py

Then paste supabase/schema.sql into the Supabase SQL editor (or psql) once.
"""
import os
import sqlite3

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DB = os.path.join(ROOT, 'fifa_2026.db')
OUT = os.path.join(ROOT, 'supabase', 'schema.sql')

# Personal betting data — never expose via the public (anon) API. RLS stays on with
# no public read policy, so only the service-role key (server-side sync) can touch it.
PRIVATE_TABLES = {'bets', 'bet_legs'}

# SQLite affinity -> Postgres type. SQLite stores datetimes as ISO text, so map
# DATETIME to text to avoid parse surprises during the bulk upsert.
TYPE_MAP = {
    'INTEGER': 'bigint',
    'REAL': 'double precision',
    'TEXT': 'text',
    'DATETIME': 'text',
    '': 'text',
}


def pg_type(sqlite_type):
    return TYPE_MAP.get((sqlite_type or '').upper(), 'text')


def main():
    con = sqlite3.connect(DB)
    tables = [r[0] for r in con.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name")]

    lines = [
        "-- Auto-generated by migrate/gen_supabase_schema.py — do not edit by hand.",
        "-- Postgres/Supabase schema mirroring fifa_2026.db. Safe to re-run.",
        "create schema if not exists public;",
        "",
    ]
    for t in tables:
        info = list(con.execute(f'PRAGMA table_info("{t}")'))
        pk = [r[1] for r in info if r[5]]
        cols = []
        for _cid, name, typ, notnull, _dflt, _ispk in info:
            col = f'  "{name}" {pg_type(typ)}'
            if notnull:
                col += ' not null'
            cols.append(col)
        if pk:
            cols.append('  primary key (' + ', '.join(f'"{c}"' for c in pk) + ')')
        lines.append(f'create table if not exists public."{t}" (')
        lines.append(',\n'.join(cols))
        lines.append(');')
        # RLS on for every table. Public tables get an anon SELECT policy; writes
        # always go through the service-role key (which bypasses RLS). Private
        # tables get NO read policy, so the anon/public API cannot read them.
        lines.append(f'alter table public."{t}" enable row level security;')
        lines.append(f'drop policy if exists "{t}_public_read" on public."{t}";')
        if t not in PRIVATE_TABLES:
            lines.append(
                f'create policy "{t}_public_read" on public."{t}" for select using (true);')
        lines.append("")
    con.close()

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f"wrote {OUT} ({len(tables)} tables)")


if __name__ == '__main__':
    main()
